### ISSUE TITLE
Documentation with any example?

### ISSUE THREAD

**Issue by limaho** [TeamNewPipe/NewPipeExtractor#229]
Can somebody explain or link to any example of how to extract stream audio for Youtube videos? I have been trying to with the documentation but there is not an exactly point of start. Also I looked in the Tests, but the library has been update so those test are not longer working.

Can somebody point me.
Thanks.

**Comment by Stypox** [comment]
The tests are up-to-date, so you can use those. Some tests fail due to network issues, but the code should be good.

**Comment by limaho** [comment]
> The tests are up-to-date, so you can use those. Some tests fail due to network issues, but the code should be good.

NewPipe.init(DownloaderTestImpl.getInstance());
            extractor = (YoutubeStreamExtractor) **YouTube**
                    .getStreamExtractor("https://www.youtube.com/watch?v=YQHsXMglC9A");
            extractor.fetchPage();

What is that YouTube class?

**Comment by imrankhanluhar** [comment]
hi same here , Can somebody explain or link to any example of how to extract stream audio for Youtube videos? I have been trying to with the documentation but there is not an exactly point of start. Also I looked in the Tests, but the library has been update so those test are not longer working.
Thanks.

**Comment by Stypox** [comment]
You can probably get some information from here: https://teamnewpipe.github.io/NewPipeExtractor/javadoc/

**Comment by TobiGr** [comment]
I just realized that the Jdoc is outdated because some tests failed. I fixed this, but there is another problem which I cannot solve atm:
`javadoc: error - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/7/docs/api/ are in the unnamed module.`
This looks like a JDK 9+ problem. @Stypox Any ideas how to solve this?

**Comment by limaho** [comment]
Could you guys explain how create the Downloader class?
I have tried many differents based on the out-date-test but I could not get it work.

`NewPipe.init(Downloader.getInstance(), new Localization("co", "es"));
        try {
            StreamingService youtube = NewPipe.getService("YouTube");
            StreamExtractor extractor = youtube.getStreamExtractor(url);
            extractor.fetchPage();
        }catch(Exception ex) {
            ex.printStackTrace();
        }`

I am having on console Downloader is null.

**Comment by bunaif** [comment]
this example use [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor) by [TeamNewPipe](https://github.com/TeamNewPipe/)

to use this example 

`
implementation 'com.github.TeamNewPipe:NewPipeExtractor:v0.17.4'
`

and add in OnCreate()

`NewPipe.init(YTDownloader.getInstance(), new Localization("en", "EN"));`

` new GetYTStreamTask(){
                    @Override
                    public void onPostExecute(String result) {
                        super.onPostExecute(result);
                        if (result != null && !result.isEmpty())
                        {
                            .....
                        }
                    }
                }.execute(youtubeLink);
`

**Comment by limaho** [comment]
I am still having issues trying to get this work. Could you somebody point me with the Downloader class.

Thanks in advance

**Comment by Stypox** [comment]
Take a look at [DownloaderTestImpl](https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/extractor/src/test/java/org/schabi/newpipe/DownloaderTestImpl.java) and implement your own downloader

**Comment by supersu-man** [comment]
> Take a look at [DownloaderTestImpl](https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/extractor/src/test/java/org/schabi/newpipe/DownloaderTestImpl.java) and implement your own downloader

The link doesn't point to any file anymore. I am getting "downloader is null" error. I am sure I am missing something.  Is there any example or a very basic code of extracting details of a youtube link please?

**Comment by supersu-man** [comment]
> Updated link: https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/extractor/src/test/java/org/schabi/newpipe/downloader/DownloaderTestImpl.java

Thank you for the quick reply. But is there any reason why this class/file is not already present in the library?

**Comment by Stypox** [comment]
Because each client may decide to use a different http stack (e.g. okhttp, cronet, ...), choose to use a cache, or apply other customizations which would determine having a different downloader. Atm NewPipe uses OkHttp and its downloader implementation is here: https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/DownloaderImpl.java

Btw, you can easily find files with the "Go to file" button and then searching "Downloader"

**Comment by supersu-man** [comment]
> Because each client may decide to use a different http stack (e.g. okhttp, cronet, ...), choose to use a cache, or apply other customizations which would determine having a different downloader. Atm NewPipe uses OkHttp and its downloader implementation is here: https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/DownloaderImpl.java
> 
> Btw, you can easily find files with the "Go to file" button and then searching "Downloader"

Thank you.

**Comment by supersu-man** [comment]
Noticed one thing, a 2mb music file is taking 2 minutes to download. I am assuming it is related to YouTube's throttling issue. Is there anything which needs to be changed to bypass that issue? Thank you.

        val httpClient = Request.Builder().url(link).build()
        val response = OkHttpClient().newCall(httpClient).execute()
        val body = response.body
        val responseCode = response.code
        if (responseCode >= HttpURLConnection.HTTP_OK && responseCode < HttpURLConnection.HTTP_MULT_CHOICE && body != null) {
            val length = body.contentLength()
            body.byteStream().apply {
                FileOutputStream(File(path)).use { output ->
                    var bytesCopied = 0L
                    val buffer = ByteArray(DEFAULT_BUFFER_SIZE)
                    var bytes = read(buffer)
                    while (bytes >= 0) {
                        output.write(buffer, 0, bytes)
                        bytesCopied += bytes
                        progress?.invoke(bytesCopied, length)
                        bytes = read(buffer)
                    }
                }
            }
        }

**Comment by supersu-man** [comment]
> Noticed one thing, a 2mb music file is taking 2 minutes to download. I am assuming it is related to YouTube's throttling issue. Is there anything which needs to be changed to bypass that issue? Thank you.

Learnt about header called 'Range' and it now instantly downloads stuff. 
` val request = Request.Builder().addHeader("Range", "bytes=0-").url(link).build()`

**Comment by shalva97** [comment]
Here is a library with okhttp wrapper in it so it's easier to try https://github.com/shalva97/NewValve

some other examples here https://github.com/shalva97/NewValve/blob/main/src/jvmTest/kotlin/Examples.kt
